name: ceka_chat
description: A simple anonymous chat app
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^2.0.3+1

flutter:
  uses-material-design: true
